### ISSUE TITLE
Export to SVG

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [wookietreiber/scala-chart#12]
http://www.jfree.org/jfreesvg/

JFreeSVG is a fast, light-weight, vector graphics library for the Java(tm) platform that makes it easy to generate graphical output in SVG format directly from Java code. The library contains:
SVGGraphics2D - generate Scalable Vector Graphics (SVG) output via standard Java2D API calls;
CanvasGraphics2D - generate Javascript code that draws to an HTML5 Canvas object;

**Comment by wookietreiber** [comment]
As it turns out, [JFreeSVG](http://www.jfree.org/jfreesvg/) is now available on [Maven Central](http://search.maven.org/#search|ga|1|jfreesvg). I am going to have a look at it.
