### ISSUE TITLE
factory for times series charts

### ISSUE THREAD

**Issue by medovina** [wookietreiber/scala-chart#16]
It would be nice to have a factory for JFreeChart's time series charts - apparently there isn't one today.

**Comment by medovina** [comment]
Aha - I didn't realize that the existing factories will automatically construct a date axis when given a TimeSeriesCollection.  So I think this is already implemented.  Closing.

**Comment by wookietreiber** [comment]
Yep, they do, whenever there is an [appropriate dataset available](https://github.com/wookietreiber/scala-chart/blob/0.4.2/src/main/scala/scalax/chart/module/ChartFactories.scala#L68). This is used by the various factories.
