### ISSUE TITLE
Charts blurry on Retina display

### ISSUE THREAD

**Issue by ruippeixotog** [wookietreiber/scala-chart#18]
When charts are shown in high-density displays such as Retina displays in MacBooks, the fonts and the lines look blurry.

There seems to be a simple fix for that [by disabling the ChartPanel buffer](http://www.jfree.org/forum/viewtopic.php?f=3&t=116775), but that will surely affect drawing performance (I don't know to what extent, though). Nonetheless, scala-chart should either support a better solution to draw charts on Retina displays or expose the `useBuffer` flag to let users decide if they want to trade quality by performance.

**Comment by wookietreiber** [comment]
I guess, I can easily add this `useBuffer` option to all swing related stuff.

However, *a better solution to draw charts* I can hardly serve because this is more of an issue the JFreeChart guys need to handle, since I only provide a Scala wrapper.

**Comment by ruippeixotog** [comment]
Of course, I was only enumerating all the alternatives :) I'd be happy to see the `useBuffer` option available to users.

**Comment by wookietreiber** [comment]
Note that I added this option only to `toComponent`, not to `toFrame` for now, because JFreeChart does not support this on `ChartFrame` either and you can only set this at `ChartPanel` instance creation time, but not afterwards.

**Comment by ruippeixotog** [comment]
Works like a charm. Thank you!
