### ISSUE TITLE
Set transparent background

### ISSUE THREAD

**Issue by sylvainlb** [wookietreiber/scala-chart#19]
I'm trying to change the theme of my chart so that it gets a transparent background, but nothing seems to apply.

I've tried:
```
val transparent = new Color(0xFF, 0xFF, 0xFF, 0)
implicit val theme: StandardChartTheme =
    org.jfree.chart.StandardChartTheme.createLegacyTheme().asInstanceOf[StandardChartTheme]
theme.setPlotBackgroundPaint(transparent)
theme.setChartBackgroundPaint(transparent)
theme.setLegendBackgroundPaint(transparent)
```

Am I doing something wrong?

**Comment by wookietreiber** [comment]
Which factory are you using?

**Comment by sylvainlb** [comment]
I'm not sure of what you call factory. I'm just doing what I just wrote, plus:

```
SpiderWebChart(data.toVector)
```

Am I answering your question?

**Comment by sylvainlb** [comment]
Same thing happens with BarChart, fyi.

**Comment by wookietreiber** [comment]
The problem you are experiencing is with the legacy chart theme, which, according to [doc](http://www.jfree.org/jfreechart/api/javadoc/org/jfree/chart/StandardChartTheme.html#createLegacyTheme--) as well to source (inspect the `StandardChartTheme.java` file) does not `apply` any settings at all (empty method).

You should create your theme as follows:

```scala
implicit val theme = new StandardChartTheme("my theme")

theme.setPlotBackgroundPaint(transparent)
theme.setChartBackgroundPaint(transparent)
theme.setLegendBackgroundPaint(transparent)
```

As an alternative, to have full control, you can implement your own `ChartTheme` from scratch.

**Comment by sylvainlb** [comment]
Oh, right sorry about that, I didn't notice LegacyChart was specific. Thanks
