### ISSUE TITLE
How to draw a chart with points instead of lines?

### ISSUE THREAD

**Issue by zie1ony** [wookietreiber/scala-chart#20]
Is there any class/object I can use to create chart with points but without lines?

I manage to do it by:

```scala
val chart = XYLineChart(series)
val renderer = new XYLineAndShapeRenderer(false, true)
chart.plot.setRenderer(renderer)
```

But is there any better way?

And how to manipulate size of point's shape?

**Comment by wookietreiber** [comment]
I am going to add a factory for this kind of chart. You have a good workaround already, there is at the moment no easier way to do this.

**Comment by zie1ony** [comment]
I cannot change shape of points to one-pixel point. Can You help me?
