### ISSUE TITLE
I'm trying to use this lib + scala 2.11

### ISSUE THREAD

**Issue by rjrussell77** [wookietreiber/scala-chart#29]
i'm using the scala-chart jar 2.10_-0.2.2.jar in Eclipse with Scala-ide plugin.
The compiler is telling me:
_

> scala-chart_2.10-0.2.2.jar of Sample Scala 2 build path is cross-compiled with an incompatible version of Scala (2.10.0). In case this report is mistaken, this check can be disabled in the compiler

_ 

Is there an update available??  How can I work around this?

**Comment by wookietreiber** [comment]
scala-chart is published on [maven](http://search.maven.org/). There you will find the latest version.
